language: java
jdk:
  - oraclejdk8
before_install:
  - git config --global user.email "travis-ci@destroystokyo.com"
  - git config --global user.name "Travis CI"
  - git submodule update --init
  - ./remap.sh
  - ./decompile.sh
  - ./init.sh
  - ./newApplyPatches.sh
after_success:
  - ./paperclip.sh
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work'